image: docker:19.03.12

services:
  - docker:dind

before_script:
  - docker info

build:
  stage: build
  script:
    - apk add --no-cache docker-compose
    - docker-compose -f docker-compose.test.yml up --build --abort-on-container-exit
    - docker-compose -f docker-compose.yaml up --build --abort-on-container-exit
