image: docker:19.03.12

services:
  - docker:dind

before_script:
  - docker info

build:
  stage: build
  script:
    - apk add --no-cache docker-compose
    - apk add --update nodejs npm
    - cd tests && npm install && npm run test
    - docker-compose up -d
