version: "3.6"

services:
  rabbitmq:
    image: rabbitmq:3
    hostname: my-rabbit
  orig:
    build:
      context: ./ORIG
      dockerfile: Dockerfile
    restart: always
    depends_on: ["rabbitmq"]
    command: npm start
  imed:
    build:
      context: ./IMED
      dockerfile: Dockerfile
    restart: always
    depends_on: ["rabbitmq"]
    command: npm start
  obser:
    build:
      context: ./OBSE
      dockerfile: Dockerfile
    volumes:
      - data:/data
    restart: always
    depends_on: ["rabbitmq"]
    command: npm start
  httpserv:
    build:
      context: ./HTTPSERV
      dockerfile: Dockerfile
    volumes:
      - data:/data
    restart: always
    command: npm start
  apigateway:
    build:
      context: ./APIGTW
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    restart: always
    command: npm start
  stateserv:
    build:
      context: ./STATESERV
      dockerfile: Dockerfile
    command: npm start
volumes:
  data:
