version: '3.6'

services:
  rabbitmq:
    image: rabbitmq:3
    hostname: my-rabbit
  orig:
    build:
      context: ./ORIG
      dockerfile: Dockerfile
    restart: always
    command: npm start
  imed:
    build:
      context: ./IMED
      dockerfile: Dockerfile
    restart: always
    command: npm start
  obser:
    build:
      context: ./OBSE
      dockerfile: Dockerfile
    volumes:
      - data:/data
    restart: always
    command: npm start
  httpserv:
    build:
      context: ./HTTPSERV
      dockerfile: Dockerfile
    volumes:
      - data:/data
    ports:
      - 8082:8082
    restart: always
    command: npm start
  apigateway:
    build:
      context: ./APIGTW
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    restart: always
    command: npm start
  stateserv:
    build:
      context: ./STATESERV
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    command: npm start
volumes:
  data:
